Added an optional timeout in the endpoint configuration of remote services
spaceuptech/space-cloud pull request #1280
Opened 2020-09-02 06:48 UTC by KavishShah09

Fixes #1277 for area/gateway

2020-09-02 07:01 UTC, sharadregoti requested changes

2020-09-02 07:01 UTC, sharadregoti commented on gateway/managers/syncman/syncman_services.go
> +			val.Timeout = int(10 * time.Second)
```suggestion
			val.Timeout = 10
```

2020-09-02 11:00 UTC, sharadregoti requested changes

2020-09-04 12:01 UTC, sharadregoti requested changes

2020-09-04 12:51 UTC, sharadregoti approved these changes

2020-09-05 07:10 UTC, YourTechBud requested changes

2020-09-05 07:10 UTC, YourTechBud commented on gateway/modules/functions/functions.go
> +
Acquire a read lock here

2020-09-05 07:10 UTC, YourTechBud commented on gateway/modules/functions/functions.go
> +func (m *Module) GetEndpointContextTimeout(ctx context.Context, service, function string) (int, error) {
Shift this function to `operations.go`

2020-09-05 07:10 UTC, YourTechBud commented on gateway/server/handlers/functions.go
> +			_ = helpers.Logger.LogError(helpers.GetRequestID(r.Context()), fmt.Sprintf("Could not find endpoint (%s) for service (%s)", serviceID, function), err, nil)
No need to log again here

2020-09-05 07:10 UTC, YourTechBud commented on gateway/server/handlers/functions.go
> +		status, result, err := functions.CallWithContext(ctx, serviceID, function, token, reqParams, req.Params)
Call the `utils.ExtractRequestParams` before this line

2020-09-06 07:25 UTC, YourTechBud approved these changes

2020-09-06 07:27 UTC, merged