Affinity support
spaceuptech/space-cloud pull request #1294
Opened 2020-09-09 07:18 UTC by sharadregoti

Fixes #1274  #1282

2020-09-09 13:06 UTC, YourTechBud requested changes

2020-09-09 13:06 UTC, YourTechBud commented on runner/utils/driver/istio/helpers.go
> +				affinityObj.Weight = -1 * affinityObj.Weight // make the weight positive
Do this within `getServiceAffinityObject`. Pass an additional multiplier field which will be multiplied with the weight

2020-09-09 13:06 UTC, YourTechBud commented on runner/utils/driver/istio/helpers.go
> +	}
Remove this

2020-09-09 13:06 UTC, YourTechBud commented on runner/utils/driver/istio/helpers.go
> +	podAntiAffinity := &v1.PodAntiAffinity{}
Declare variable and let it be nil

2020-09-09 13:06 UTC, YourTechBud commented on runner/utils/driver/istio/helpers.go
> +				required, preferred := getServiceAffinityObject(affinity)
Initialise affinity object here if nil

2020-09-09 13:06 UTC, YourTechBud commented on runner/utils/driver/istio/helpers.go
> +				affinityObj := affinity
Initialise anti affinity object here

2020-09-09 13:06 UTC, YourTechBud commented on runner/utils/driver/istio/helpers.go
> +			// affinity
Initialise nodeAffinity object here if nil

2020-09-09 13:06 UTC, YourTechBud commented on runner/utils/driver/istio/helpers.go
> +	preferred := []v1.WeightedPodAffinityTerm{}
Why array?

2020-09-09 13:06 UTC, YourTechBud commented on runner/utils/driver/istio/helpers.go
> +func getNodeAffinityObject(affinity model.Affinity) (*v1.NodeSelector, []v1.PreferredSchedulingTerm) {
Return the NodeSelectorTerm

2020-09-09 15:09 UTC, sharadregoti commented on gateway/modules/crud/sql/raw.go
> +		sql = fmt.Sprintf("create database if not exists `%s`", name)
Yes

2020-09-09 15:14 UTC, sharadregoti commented on runner/utils/driver/istio/get.go
> +		for _, nodeSelectorTerm := range deployment.Spec.Template.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
Not possible because the type of NodeSelectorTerms is different

2020-09-12 05:16 UTC, YourTechBud requested changes

2020-09-12 05:16 UTC, YourTechBud commented on runner/utils/driver/istio/get.go
> +		for _, preferredSchedulingTerm := range deployment.Spec.Template.Spec.Affinity.NodeAffinity.PreferredDuringSchedulingIgnoredDuringExecution {
Make another extract function then. Don't make the code here too lengthy

2020-09-12 05:16 UTC, YourTechBud commented on runner/utils/driver/istio/get.go
> +		for _, nodeSelectorTerm := range deployment.Spec.Template.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
Make another extract function then. Don't make the code here too lengthy

2020-09-12 05:16 UTC, YourTechBud commented on runner/utils/driver/istio/get.go
> +		delete(labels, "app")
No need to delete these labels

2020-09-12 06:49 UTC, YourTechBud approved these changes

2020-09-12 06:49 UTC, merged