Service-Role
spaceuptech/space-cloud pull request #1368
Opened 2020-10-20 07:40 UTC by prithvi081099

2020-10-20 16:37 UTC, sharadregoti requested changes

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/get.go
> +	rolelist, err1 := i.kube.RbacV1().Roles(ns).List(ctx, metav1.ListOptions{})
Add a label selector in listOptions{} struct.
"app.kubernetes.io/managed-by=space-cloud"
And handle error seperately

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/get.go
> +	clusterRoleList, err2 := i.kube.RbacV1().ClusterRoles().List(ctx, metav1.ListOptions{})
Add a label selector in listOptions{} struct.
"app.kubernetes.io/managed-by=space-cloud"
And handle error seperately

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/get.go
> +	if err1 == nil {
This if is not required, as it will always be nil

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/get.go
> +			var Role model.Role
This variable will be nil, use new() function

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/get.go
> +}
same here

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/delete_helpers.go
> +	if kubeErrors.IsNotFound(err) {
```suggestion
	if !kubeErrors.IsNotFound(err) {
```

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/delete_helpers.go
> +	if kubeErrors.IsNotFound(err) {
```suggestion
	if !kubeErrors.IsNotFound(err) {
```

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/delete_helpers.go
> +		return err
check err for roles functions & use helpers.logger to log error

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/delete_helpers.go
> +	_, err := i.kube.RbacV1().Roles(projectID).Get(ctx, id, metav1.GetOptions{})
```suggestion
	_, err1 := i.kube.RbacV1().Roles(projectID).Get(ctx, id, metav1.GetOptions{})
```

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/delete_helpers.go
> +	_, err = i.kube.RbacV1().ClusterRoles().Get(ctx, id, metav1.GetOptions{})
```suggestion
	_, err2 = i.kube.RbacV1().ClusterRoles().Get(ctx, id, metav1.GetOptions{})
```

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/delete_helpers.go
> +	return helpers.Logger.LogError(helpers.GetRequestID(ctx), fmt.Sprintf("Specified role id-(%v) was not present", id), nil, nil)
Log this if err1 & err2 is not nill

2020-10-20 16:37 UTC, sharadregoti commented on runner/utils/driver/istio/delete.go
> +		return helpers.Logger.LogError(helpers.GetRequestID(ctx), "Could not delete service role", err, nil)
```suggestion
		return helpers.Logger.LogError(helpers.GetRequestID(ctx), fmt.Sprintf("Unable to delete service role (%s)",id), err, nil)
```

2020-10-21 11:11 UTC, sharadregoti requested changes

2020-10-21 11:11 UTC, sharadregoti commented on runner/utils/driver/istio/helpers.go
> +			APIGroup: DefaultAPIGroup,
```suggestion
			APIGroup: role.Project, // For all roles in the "projectID" namespace:


```

2020-10-21 11:11 UTC, sharadregoti commented on runner/utils/driver/istio/helpers.go
> +				APIGroup: DefaultAPIGroup,
```suggestion
				APIGroup: role.Project, // For all service accounts in the "projectID" namespace:


```

2020-10-21 11:11 UTC, sharadregoti commented on runner/utils/driver/istio/helpers.go
> +			Namespace: role.Project,
Remove namespace field

2020-10-21 11:11 UTC, sharadregoti commented on space-cli/cmd/modules/services/commands.go
> +		Aliases: []string{"service-role"},
```suggestion
		Aliases: []string{"service-roles"},
```

2020-10-21 11:11 UTC, sharadregoti commented on space-cli/cmd/modules/services/commands.go
> +		Example: "space-cli generate service-role config.yaml --project myproject --log-level info",
```suggestion
		Example: "space-cli generate service-role config.yaml --project myproject",
```

2020-10-21 11:11 UTC, sharadregoti commented on space-cli/cmd/modules/services/commands.go
> +					serviceIds = append(serviceIds, v.Meta["serviceID"])
are you sure ID capital rahega, i think it will be Id

2020-10-21 11:11 UTC, sharadregoti commented on space-cli/cmd/modules/services/commands.go
> +					roleID = append(roleID, v.Meta["roleID"])
Same here

2020-10-21 11:11 UTC, sharadregoti commented on space-cli/cmd/modules/services/generate.go
> +		apiGroups := strings.Split(apiGroup, ",")
Handle the case, when the last element after comma is not specified
a,b,c,
you array will [a,b,c,""]

2020-10-21 11:11 UTC, sharadregoti commented on space-cli/cmd/modules/services/generate.go
> +	if err := input.Survey.AskOne(&survey.Input{Message: "Enter Type:"}, &Type); err != nil {
Use select for type

2020-10-22 05:57 UTC, sharadregoti requested changes

2020-10-22 05:57 UTC, sharadregoti commented on install-manifests/kubernetes/space-cloud.yaml
>  ---
Revert these change when you are done testing

2020-10-23 03:42 UTC, sharadregoti requested changes

2020-10-23 03:42 UTC, sharadregoti commented on runner/utils/driver/istio/get.go
> +		Role.Type = "Project"
Use the constant that you defined

2020-10-23 03:42 UTC, sharadregoti commented on runner/utils/driver/istio/get.go
> +		Role.Type = "Cluster"
Same here

2020-10-23 04:40 UTC, sharadregoti requested changes

2020-10-23 04:40 UTC, sharadregoti commented on runner/utils/driver/istio/delete.go
> +		return helpers.Logger.LogError(helpers.GetRequestID(ctx), fmt.Sprintf("Unable to delete service role (%s)", id), err, nil)
```suggestion
		return err
```

2020-10-24 10:17 UTC, YourTechBud requested changes

2020-10-24 10:17 UTC, YourTechBud commented on runner/utils/driver/istio/helpers.go
> +	labels["space-cloud.io/version"] = model.Version
Dont do this. Create a literal map directly below

2020-10-24 10:20 UTC, sharadregoti commented on runner/utils/driver/istio/apply.go
> +		ServiceRole := i.generateServiceRole(ctx, role)
:see_no_evil: :rofl:

2020-10-26 04:49 UTC, sharadregoti approved these changes

2020-10-26 05:25 UTC, YourTechBud approved these changes

2020-10-26 05:34 UTC, merged