Driver Configuration Parameters
spaceuptech/space-cloud pull request #1374
Opened 2020-10-23 06:15 UTC by KhushalPShah

I have added the following Parameters for the driver configuration for MongoDb and SQL : 
MaxConn           (for SQL and Mongo)
MaxIdleTimeout (for SQL and Mongo)
MinConn             (only for Mongo)
MaxIdleConn       (only for SQL)

2020-10-24 07:41 UTC, YourTechBud requested changes
Run `go mod tidy` once

2020-10-24 07:41 UTC, YourTechBud commented on gateway/config/config.go
> +	MaxConn        int    //for SQL and Mongo
Add json and yaml annotations

2020-10-24 07:41 UTC, YourTechBud commented on gateway/config/config.go
> +	DriverConf   DriverConfig
Add json and yaml annotations

2020-10-24 07:41 UTC, YourTechBud commented on gateway/modules/crud/mgo/mongo.go
> +	return ((strings.HasPrefix(m.connection, conn)) && (dbName == m.dbName) && (driverConf.MaxConn == m.driverConf.MaxConn) && (driverConf.MaxIdleTimeout == m.driverConf.MaxIdleTimeout) && (driverConf.M
No need to use parenthesis at all here since each one is an and clause

2020-10-24 07:41 UTC, YourTechBud commented on gateway/modules/crud/mgo/mongo.go
> +	opts = opts.SetMaxPoolSize((uint64)(m.driverConf.MaxConn))
Set default values for each one of the driver configs first. However, don't overwrite the driver conf object, make new variables

2020-10-24 07:41 UTC, YourTechBud commented on gateway/modules/crud/mgo/mongo.go
> +	}
duration = time.Duration(m.driverConf.MaxIdleTimeout) * time.Milliseconds

2020-10-24 07:41 UTC, YourTechBud commented on gateway/modules/crud/sql/sql.go
> +	return ((strings.HasPrefix(s.connection, conn)) && (dbName == s.name) && (driverConf.MaxConn == s.driverConf.MaxConn) && (driverConf.MaxIdleTimeout == s.driverConf.MaxIdleTimeout) && (driverConf.Max
No need to use parenthesis at all

2020-10-24 07:41 UTC, YourTechBud commented on gateway/modules/crud/sql/sql.go
> +	s.client.SetMaxOpenConns(s.driverConf.MaxConn)
Set default values if the driver config value is zero

2020-10-24 07:41 UTC, YourTechBud commented on gateway/modules/crud/sql/sql.go
> +	}
duration = time.Duration(m.driverConf.MaxIdleTimeout) * time.Milliseconds

2020-10-26 04:51 UTC, sharadregoti commented
@KhushalPShah Your build is failing, fix it

2020-10-26 06:12 UTC, YourTechBud approved these changes

2020-10-26 06:38 UTC, merged

2020-10-26 06:41 UTC, YourTechBud commented
Fixed #1023