Filestore space cli deleters
spaceuptech/space-cloud pull request #1378
Opened 2020-10-23 12:50 UTC by KavishShah09

fixes #1155 for filestore module

2020-10-24 11:24 UTC, sharadregoti requested changes

2020-10-24 11:24 UTC, sharadregoti commented on gateway/managers/syncman/syncman_file.go
> +}
I don't think so this is required, you just call the set file store config endpoint with all the required values in the payload as empty

2020-10-24 11:24 UTC, sharadregoti commented on space-cli/cmd/modules/filestore/commands.go
> +		Example:           "space-cli delete filestore-rules ruleID --project myproject --log-level info",
Remove --log level info from usage.
Do this everywhere

2020-10-24 11:24 UTC, sharadregoti commented on space-cli/cmd/utils/filter/filter.go
> +func DeleteOptions(prefix string, resources []string, doesResourceExist bool) (string, error) {
chnage line number 15 to
		if prefix != "" && strings.HasPrefix(strings.ToLower(resource), strings.ToLower(prefix)) && prefix != resource{

And remove the if at line number 22, always show the filtered resources

2020-10-25 08:59 UTC, KavishShah09 commented
@sharadregoti please add `hacktoberfest-accepted` label to this

2020-10-26 04:58 UTC, sharadregoti approved these changes

2020-10-26 05:02 UTC, merged