WIP: Letsencrypt, project, remote-services, secrets deleters
spaceuptech/space-cloud pull request #1385
Opened 2020-10-31 04:23 UTC by KavishShah09

fixes #1155 for letencrypt, project, remote-services and secrets

2020-11-03 13:47 UTC, KavishShah09 commented
@sharadregoti can you review this

2020-11-08 05:49 UTC, sharadregoti requested changes

2020-11-08 05:49 UTC, sharadregoti commented on gateway/server/handlers/config_letsencrypt.go
> +func HandleDeleteLetsEncryptWhitelistedDomain(adminMan *admin.Manager, syncMan *syncman.Manager) http.HandlerFunc {
This endpoint is not required. Call the set endpoint with the empty body

2020-11-08 05:49 UTC, sharadregoti commented on gateway/server/routes.go
> +	router.Methods(http.MethodDelete).Path("/v1/config/projects/{project}/letsencrypt/config/{id}").HandlerFunc(handlers.HandleDeleteLetsEncryptWhitelistedDomain(s.managers.Admin(), s.managers.Sync()))
Not required

2020-11-09 13:21 UTC, sharadregoti approved these changes

2020-11-09 13:22 UTC, merged