deleters of service and service-role
spaceuptech/space-cloud pull request #1470
Opened 2020-12-26 17:05 UTC by prithvi081099

Fix #1155

2020-12-29 07:04 UTC, sharadregoti requested changes

2020-12-30 06:03 UTC, sharadregoti requested changes

2020-12-30 06:03 UTC, sharadregoti commented on space-cli/cmd/modules/services/delete_test.go
> +	}
Add some test cases for 

- Exact match
- User has provided both service id & version
- Add more services in, Get services HTTP call

2020-12-30 06:03 UTC, sharadregoti commented on space-cli/cmd/modules/services/delete_test.go
> +		// TODO: Add test cases.
Remove this & do the same here

2021-01-02 04:15 UTC, sharadregoti approved these changes

2021-01-02 06:32 UTC, YourTechBud requested changes

2021-01-02 06:32 UTC, YourTechBud commented on space-cli/cmd/modules/services/commands.go
> +		Use:               "service-routes",
Plural form must be in alias

2021-01-02 06:32 UTC, YourTechBud commented on space-cli/cmd/modules/services/commands.go
> +		Use:               "service-role",
Plural form must be in alias

2021-01-02 06:32 UTC, YourTechBud commented on space-cli/cmd/modules/services/commands.go
> +		Use:               "services",
Plural form must be in alias

2021-01-02 06:32 UTC, YourTechBud commented on space-cli/cmd/modules/services/generate.go
> +			if err := input.Survey.AskOne(&survey.Input{Message: "No default registry configured, provide registry"}, &reg); err != nil {
Add an example `gcr.io/spaceuptech`

2021-01-05 04:09 UTC, YourTechBud approved these changes

2021-01-05 04:09 UTC, merged