eventing changes
spaceuptech/space-cloud pull request #1502
Opened 2021-01-17 06:37 UTC by sharadregoti

1) Optimized eventing modules to process staged events with buffer.

2021-01-17 06:38 UTC, sharadregoti commented
Fixes #1480

2021-01-22 10:24 UTC, YourTechBud requested changes

2021-01-22 10:24 UTC, YourTechBud commented on gateway/config/config.go
> +	ProcessingConfig int              `json:"processingConfig" yaml:"processingConfig" mapstructure:"processingConfig"`
Call this `MaxWorkers`

2021-01-22 10:24 UTC, YourTechBud commented on gateway/config/config.go
> +	ProcessingConfig int                         `json:"processingConfig" yaml:"processingConfig" mapstructure:"processingConfig"`
Call this MaxProcessiors

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/broadcast.go
> +	fmt.Println("Length of process transmitted events", len(eventDocs))
Why is this here?

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/crud.go
> +	fmt.Println("Request", ev.req.Find)
Remove this

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/eventing.go
> +	fmt.Println("Current p config vs new p config", m.config.ProcessingConfig, eventing.ProcessingConfig)
Remove this

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/eventing.go
> +		fmt.Println("Provided processing config is 0, default to", utils.DefaultEventProcessingConfig)
Make this warning

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/eventing.go
> +		_ = fmt.Sprintf("Processing config has been changed from (%d) to (%d)", m.config.ProcessingConfig, eventing.ProcessingConfig)
WHY?

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/eventing.go
> +		m.bufferedEventProcessingRoutineCloser <- struct{}{}
Close this channel instead

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/eventing.go
> +		m.bufferedEventProcessingChannel = make(chan *model.EventDocument, eventing.ProcessingConfig*3)
After thinking about this. Lets hard code the parallel worker count. Putting locks on channels isn't a good thing. We have to use locks if this channel size will be variable

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/handle_staged.go
> +	count := 0
Remove

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/helpers.go
> +	m.lock.Lock()
We don't need a lock here if we never have to close the channel

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/eventing.go
> +	fmt.Println("Check complete of eventing 2")
Remove this

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/eventing.go
> +	close(m.globalCloserChannel)
Did you check if this actually closed all the goroutines

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/routine.go
> +			fmt.Println("Closing routineProcessStaged")
Remove this

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/routine.go
> +			close(m.updateFailedEventInDBChannel)
You can close this channel. Only the person writing to the channel is allowed to close the channel

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/routine.go
> +	duration := 1 * time.Second
Make this 250 milliseconds

2021-01-22 10:24 UTC, YourTechBud commented on gateway/modules/eventing/routine.go
> +			passiveArr := activeArr
This is wrong. Passive array needs to be declared alongside active array. Set the value of the passive array to active array after you done deleting values of previouspassive array. Then make a new active array

2021-01-26 06:51 UTC, YourTechBud requested changes

2021-01-26 06:51 UTC, YourTechBud commented on gateway/modules/eventing/routine.go
> +			arr = append(arr, ev)
We should immediately flush the updates if array length exceeds 200

2021-01-26 06:51 UTC, YourTechBud commented on gateway/modules/eventing/routine.go
> +			m.queueUpdateEvent(ev)
I suggest we rename this function. Because it isn't really queuing anything.

2021-01-26 06:51 UTC, YourTechBud commented on gateway/modules/eventing/routine.go
> +			// TODO: Do i require a lock here
No really. Since it all going to close

2021-01-31 04:41 UTC, YourTechBud submitted a review, later dismissed

2021-02-02 06:52 UTC, YourTechBud approved these changes

2021-02-02 06:56 UTC, merged